{% set version = "4.1.0" %}

package:
    name: qutip
    version: {{ version }}

source:
    fn: qutip-{{ version }}.tar.gz
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: b41963d33662121d3f996c5c4f8f28a63c5253d5ffb3f4e1a4e88d84e213b006

build:
    number: 1
    script: $PYTHON setup.py install  # [unix]
    # ajgpitch 2017-03-16: win py27 build currently failing due to error on import scipy.misc
    # Trying again on a new build
    # skip: True                        # [win and py2k]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython >=0.21
    - scipy >=0.15
    - mingwpy                         # [win and py2k]
    - toolchain
    
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.15
    - cython >=0.21
    - mingwpy                         # [win and py2k]
    
test:
  commands:
    - echo "NUMBER_OF_PROCESSORS"
    - echo "%NUMBER_OF_PROCESSORS%"

about:
    home: http://qutip.org
    license: BSD 3-clause
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - sahmed95
    - nonhermitian
